#!/usr/bin/perl
#
# Very simple, a little bit ugly
# Given a file and an $CFG variable extract it's value
# maybe convert to a file that parses the php and turns into
# a make compatible variable file and then import it

use strict;

if ($#ARGV ne 2){
    print <<EOF;
Usage:

$0 file CFGobj CFGattr
EOF
    exit 1;
}
my $file = $ARGV[0];
my $CFG = $ARGV[1];
my $var = $ARGV[2];
open(my $FILE, $file) or die "Can't read $file for $CFG -> $var";
my @lines = <$FILE>;
close $FILE;

# Strip comments
@lines = map { $_ =~ s/#.*$//g; $_ } @lines;
@lines = map { $_ =~ s/^\/\/.*$//g; $_ } @lines;
@lines = map { $_ =~ s/\s\/\/.*$//g; $_ } @lines;


@lines = grep (/$var/, @lines);

# Now ditch empty lines
@lines = grep { $_ ne '' } @lines;

# extract var
@lines = grep (s/^.*\$$CFG->$var.*'(.*)'.*$/$1/g , @lines);

if ($#lines eq 0){
    print @lines;
} else {
    die "Didn't find a single unique value (".($#lines+1).") for $file for $CFG -> $var\n" . (join "\n",  @lines);
}


